[project]
name = "comfyui-if_ai_hfdownloadernode"
description = "Downloads repos/spaces and individual files from HuggingFace"
version = "1.0.1"
license = "LICENSE"
dependencies = ["huggingface_hub"]

[project.urls]
Repository = "https://github.com/if-ai/ComfyUI-IF_AI_tools"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "impactframes"
DisplayName = "ComfyUI-IF_AI_HFdownloader"
Icon = "ğŸ’¥ğŸï¸"
